config/routes.rb
# frozen_string_literal: true

# Copyright 2019 Andrew Esler (ajesler)
# Copyright 2019 Steven C Hartley
# Copyright 2020 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "sidekiq/web"
require "sidekiq-scheduler/web"

# For more information about routes, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: "landing#index"

  # Sidekiq is our jobs server and keeps tabs on backround tasks
  if ENV["SIDEKIQ_USER"].present? && ENV["SIDEKIQ_PASSWORD"].present?
    # Mounting /sidekiq with basic auth
    mount Sidekiq::Web, at: "/sidekiq"

    Sidekiq::Web.use Rack::Auth::Basic  do |username, password|
      user_provided = ::Digest::SHA256.hexdigest(username)
      user_expected = ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USER"])

      password_provided = ::Digest::SHA256.hexdigest(password)
      password_expected = ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"])

      user_ok = ActiveSupport::SecurityUtils.secure_compare(user_provided, user_expected)
      password_ok = ActiveSupport::SecurityUtils.secure_compare(password_provided, password_expected)

      (user_ok && password_ok)
    end
  elsif ENV["SIDEKIQ_NO_PASSWORD"].present?
    # Mounting /sidekiq without password
    mount Sidekiq::Web, at: "/sidekiq"
  else
    # Not mounting /sidekiq
  end

  # Sets routes for account management actions.
  # This order seems to matter for tests.
  devise_for :users
  devise_for :operators

  # Before 2020-07 the Operator model was called Support
  # This is in place to help migrate people who log in to move to the new model
  get "/supports/sign_in", to: redirect("/operators/sign_in")

  get "/login/:email/:key", to: "user_tokens#kansa_login_link", email: /[^\/]+/, key: /[^\/]+/
  resources :user_tokens, only: [:new, :show, :create], id: /[^\/]+/ do
    get :logout, on: :collection
  end

  resources :credits
  resources :landing
  resources :memberships
  resources :themes
  resources :upgrades
  resources :hugo_packet, id: /[^\/]+/

  resources :reservations do
    resources :charges
    resources :finalists, id: /[^\/]+/
    resources :nominations, id: /[^\/]+/
    resources :upgrades
  end

  # /operator are maintenance routes for support people
  namespace :operator do
    resources :users do
      resources :the_fantasy_network_roles
      resources :notes
    end

    resources :reservations do
      resources :credits
      resources :set_memberships
      resources :transfers, id: /[^\/]+/
      resources :rights
    end
  end
end

app/models/operator.rb
# frozen_string_literal: true

# Copyright 2020 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Operator is not a User, but does present a login means for people who need to access admin pages
# This relies on Devise for handling cookies and sessions and inherits from global config set in config/initializers/devise.rb
# Operator actions live on URLs prefixed with /operator
# Operator#hugo_admin property exists for sensitive actions that Hugo Admins want exclusive control over, set this to true to alter Nomination forms
# You can use these credentials to sign in through /operators/sign_in
class Operator < ApplicationRecord
  # Currently you create Operator users thorugh the rails console with Operator.create!(email: "...", password: "...")
  # However this can be configured to use Google or Facebook auth instead
  # Please open a MR if you want to do this, and make it configurable plz <3

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :omniauthable, :registerable, :recoverable
  devise :database_authenticatable, :rememberable, :validatable, :trackable, :confirmable, :lockable
end

app/controllers/operator/credits_controller.rb
# frozen_string_literal: true

# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# CreditsController allows us to list and grant account credit to a user
class Operator::CreditsController < ApplicationController
  before_action :authenticate_operator!
  before_action :lookup_reservation!

  def new
    @amount_owed = AmountOwedForReservation.new(@reservation).amount_owed
    @credit = PlanCredit.new
  end

  def create
    credit_params = params.require(:plan_credit).permit(:amount)
    plan = PlanCredit.new(credit_params)
    if !plan.valid?
      flash[:error] = plan.errors.full_messages.to_sentence
      redirect_to @reservation
      return
    end

    ApplyCredit.new(@reservation, plan.money, audit_by: current_operator.email).call
    flash[:notice] = "Credited ##{@reservation.membership_number} with #{plan.money.format}"
    redirect_to @reservation
  end
end

app/controllers/operator/notes_controller.rb
# frozen_string_literal: true

# Copyright 2020 Matthew B. Gray
# Copyright 2020 Steven Ensslen
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NotesController creates arbitary notes against users. Notes are supposed to be written but never modified.
class Operator::NotesController < ApplicationController
  before_action :authenticate_operator!
  before_action :lookup_user!

  def create
    @user.notes.create!(content: params[:content])
    redirect_to operator_user_path(@user)
  end
end

app/controllers/operator/rights_controller.rb
# frozen_string_literal: true

# Copyright 2020 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Operator::RightsController < ApplicationController
  before_action :authenticate_operator!
  before_action :lookup_reservation!

  # create modifies the rights on the underlying reservation rather than creating a new one. This bends convention
  # slightly because separating setting of rights from other user actions on reservation makes it easier to make sure
  # it's not part of the user flows. If you want to inline this, maybe consider detection of user intent through various
  # strong param lookups
  def create
    if !@reservation.disabled?
      @reservation.update!(state: Reservation::DISABLED)
    elsif instalment?
      @reservation.update!(state: Reservation::INSTALMENT)
    else
      @reservation.update!(state: Reservation::PAID)
    end

    if @reservation.disabled?
      flash[:notice] = "Disabled membership rights for member ##{@reservation.membership_number}"
    else
      flash[:notice] = "Enabled membership rights for member ##{@reservation.membership_number}"
    end

    redirect_to reservation_path(@reservation)
  end

  private

  def instalment?
    shortfall > 0
  end

  def shortfall
    AmountOwedForReservation.new(@reservation).amount_owed
  end
end

app/controllers/operator/set_memberships_controller.rb
# frozen_string_literal: true

# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Operator::SetMembershipsController < ApplicationController
  before_action :authenticate_operator!
  before_action :lookup_reservation!

  def index
    @memberships = Membership.all
    @as_at = Time.now
  end

  def update
    membership = Membership.find(params[:id])
    SetMembership.new(@reservation, to: membership, audit_by: current_operator.email).call
    flash[:notice] = "Set ##{@reservation.membership_number} to #{membership}"
    redirect_to @reservation
  end
end

app/controllers/operator/the_fantasy_network_roles_controller.rb
# Copyright 2020 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Operator::TheFantasyNetworkRolesController < ApplicationController
  before_action :authenticate_operator!
  before_action :lookup_user!
  before_action :lookup_gloo_contact!

  def index
    all_roles = as_hash(GlooContact::DISCORD_ROLES, value: false)
    remote_roles = as_hash(@gloo_contact.discord_roles, value: true)
    @current_roles = all_roles.merge(remote_roles)
  end

  def create
    @gloo_contact.discord_roles = posted_discord_roles
    @gloo_contact.save!
    redirect_to operator_user_the_fantasy_network_roles_path(@user)
  end

  private

  def posted_discord_roles
    GlooContact::DISCORD_ROLES.select { |role| params[role] == "1" }
  end

  # converts ["Discord_ConCom", "Discord_Mission_Control"]
  # to { Discord_ConCom: true, Discord_Mission_Control: true }
  def as_hash(list, value:)
    list.zip([value]*list.length).to_h
  end
end

app/controllers/operator/transfers_controller.rb
# frozen_string_literal: true

# Copyright 2020 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Operator::TransfersController < ApplicationController
  helper ReservationsHelper

  before_action :authenticate_operator!
  before_action :setup_transfer, only: [:show, :update]

  def new
    @reservation = Reservation.find(params[:reservation_id])
    @contact = @reservation.active_claim.contact
  end

  def show
  end

  def create
    @reservation = Reservation.find(params[:reservation_id])
    redirect_to operator_reservation_transfer_path(params[:email], reservation_id: @reservation)
  end

  def update
    current_operator.transaction do
      owner_contact = @transfer.copy_contact

      service = ApplyTransfer.new(
        @transfer.reservation,
        from: @transfer.from_user,
        to: @transfer.to_user,
        audit_by: current_operator.email,
        copy_contact: @transfer.copy_contact?,
      )
      new_claim = service.call
      if !new_claim
        flash[:error] = service.error_message
        redirect_to reservations_path
        return
      end

      MembershipMailer.transfer(
        from: @transfer.from_user.email,
        to: @transfer.to_user.email,
        owner_name: owner_contact&.to_s,
        membership_number: @transfer.reservation.membership_number,
      ).deliver_later

      flash[:notice] = %{
        Transferred membership ##{@transfer.reservation.membership_number}
        to #{@transfer.to_user.email}
      }

      redirect_to reservations_path
    end
  end

  private

  def setup_transfer
    @transfer = PlanTransfer.new(
      new_owner: params[:id],
      reservation_id: params[:reservation_id],
      copy_contact: params.dig("plan_transfer", "copy_contact"),
    )

    if !@transfer.valid?
      flash[:error] = @transfer.errors.full_messages.to_sentence
      redirect_to reservations_path
    end
  end
end

app/controllers/operator/users_controller.rb
# Copyright 2020 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Operator::UsersController is the CoNZealand admin for virtual attendance
# It integartes with a 3rd party login provider called Gloo
class Operator::UsersController < ApplicationController
  before_action :authenticate_operator!
  before_action :lookup_user!, except: :index
  before_action :lookup_gloo_contact!, except: :index

  def index
  end

  def show
  end

  def update
    @gloo_contact.save!
    flash[:notice] = just_saved_message
    redirect_to operator_user_path(@user)
  end

  private

  def just_saved_message
    if membership_number = @gloo_contact.reservation&.membership_number
      "Pushed #{@user.email} to TFN with membership ##{membership_number}"
    else
      "Disabled #{@user.email} on TFN"
    end
  end
end

app/views/operator/transfers/new.html.erb
<%#
  Copyright 2020 Matthew B. Gray

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<h1>Transferring Membership:</h1>
<section class="l-section">
  <div class="row">
    <div class="col-12 col-md-12">
      <div class="l-panel">
        <h2>
          From
          <%= @contact %>
          &lt;<%= @reservation.user.email %>&gt;
        </h2>

        <p>
          This process will send email to <%= @contact || @reservation.user.email %> and the new email address.
        </p>
      </div>

      <div class="l-panel">
        <h2>
          Current Membership Holder:
        </h2>
        <h4>
          <%= @detail %>
          <%= @reservation.user.email %>
        </h4>
        </div>

        <div class="l-panel">
          <h2>
            Membership Recipient:
          </h2>
          <h4>
            Enter recipient's email OR select a previously-registered user:
          </h4>
          <%= form_with(url: operator_reservation_transfers_path(reservation_id:  @reservation), method: :post, local: true) do |f| %>
              <%= f.text_field :email %>
              <%= submit_tag("Submit", class: "btn") %>
          <% end %>
          <h4>
            Search or browse existing users:
          </h4>
          <p>
            Users listed below would have signed in at least once so we know they have access to their account
          </p>

        <table class="js-data-table table table-hover table-striped table-dark table-borderless table-responsive-lg">
          <thead>
            <th>Email</th>
            <th>Membership Details</th>
          </thead>
          <tbody>
            <%= User.eager_load(active_claims: :contact).find_each do |user| %>
              <tr>
                <td><%= link_to user.email, operator_reservation_transfer_path(user.email, reservation_id: @reservation)  %></td>
                <td><%= user.active_claims.map(&:contact).map(&:to_s).to_sentence %></td>
              </p>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/operator/transfers/show.html.erb
<%#
  Copyright 2019 Matthew B. Gray

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>
<h1>Transferring Membership: Confirm transfer</h1>
<section class="l-section">
  <div class="row">
    <div class="col-12 col-md-12">
      <div class="l-panel">
        <%= form_for(@transfer, method: :patch, url: update_transfer_path(@transfer)) do |f| %>
          <h2>#<%= @transfer.reservation.membership_number %> <%= @transfer.copy_contact %></h2>
          <p>Transferring from <%= @transfer.from_user.email %></p>
          <p>Transferring to <%= @transfer.to_user.email %><p>

          <div class="form-options">
            <%= f.check_box(:copy_contact, class: "form-control form-control-m-checkbox", id: "copy_contact") %>
            <label for="copy_contact">Keep membership details? This includes name, badge name, and address</label>
          </div>

          <fieldset class="l-v-spacing">
            <div class="row">
              <div class="col-12 col-md-6">
                <div class="l-v-spacing">
                  <%= link_to "Go back to transfer list", new_operator_reservation_transfer_path, class: "btn btn-m-full-width" %>
                </div>
              </div>
              <div class="col-12 col-md-6">
                <div class="l-v-spacing">
                  <input type="submit" value="Email users and transfer membership" class="btn btn-m-full-width">
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>