config/routes.rb
# frozen_string_literal: true

# Copyright 2019 Andrew Esler (ajesler)
# Copyright 2019 Steven C Hartley
# Copyright 2020 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "sidekiq/web"
require "sidekiq-scheduler/web"

# For more information about routes, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: "landing#index"

  # Sidekiq is our jobs server and keeps tabs on backround tasks
  if ENV["SIDEKIQ_USER"].present? && ENV["SIDEKIQ_PASSWORD"].present?
    # Mounting /sidekiq with basic auth
    mount Sidekiq::Web, at: "/sidekiq"

    Sidekiq::Web.use Rack::Auth::Basic  do |username, password|
      user_provided = ::Digest::SHA256.hexdigest(username)
      user_expected = ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USER"])

      password_provided = ::Digest::SHA256.hexdigest(password)
      password_expected = ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"])

      user_ok = ActiveSupport::SecurityUtils.secure_compare(user_provided, user_expected)
      password_ok = ActiveSupport::SecurityUtils.secure_compare(password_provided, password_expected)

      (user_ok && password_ok)
    end
  elsif ENV["SIDEKIQ_NO_PASSWORD"].present?
    # Mounting /sidekiq without password
    mount Sidekiq::Web, at: "/sidekiq"
  else
    # Not mounting /sidekiq
  end

  # Sets routes for account management actions.
  # This order seems to matter for tests.
  devise_for :users
  devise_for :operators

  # Before 2020-07 the Operator model was called Support
  # This is in place to help migrate people who log in to move to the new model
  get "/supports/sign_in", to: redirect("/operators/sign_in")

  get "/login/:email/:key", to: "user_tokens#kansa_login_link", email: /[^\/]+/, key: /[^\/]+/
  resources :user_tokens, only: [:new, :show, :create], id: /[^\/]+/ do
    get :logout, on: :collection
  end

  resources :credits
  resources :landing
  resources :memberships
  resources :themes
  resources :upgrades
  resources :hugo_packet, id: /[^\/]+/

  resources :reservations do
    resources :charges
    resources :finalists, id: /[^\/]+/
    resources :nominations, id: /[^\/]+/
    resources :upgrades
  end

  # /operator are maintenance routes for support people
  namespace :operator do
    resources :users do
      resources :the_fantasy_network_roles
      resources :notes
    end

    resources :reservations do
      resources :credits
      resources :set_memberships
      resources :transfers, id: /[^\/]+/
      resources :rights
    end
  end
end

app/controllers/themes_controller.rb
# frozen_string_literal: true

# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ThemesController allows users to browse and work on Themes for their con without
# needing to browse around the entire con website. From here you get a feel for how things will render
class ThemesController < ApplicationController
  LAYOUTS = "app/views/layouts"

  layout -> { params[:id] }, only: :show

  def index
    layouts = Dir.each_child("#{Rails.root}/#{LAYOUTS}").to_a
    html_layouts = layouts.select { |file| file.match(/html/) }
    @themes = html_layouts.map { |file| file.gsub(/\.html.*/, "") }
  end

  def show
  end
end

app/views/themes/index.html.erb
<%#
  Copyright 2019 Matthew B. Gray

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>
<p>
This is a work in progress. If you're looking to build a enw theme just get in touch and we'll
figure out how to fit it in here :).
</p>

<p>
Here's all the html layouts found inside <%= ThemesController::LAYOUTS %>
</p>

<p>
  <ul>
    <% @themes.each do |theme| %>
      <li>
        <%= link_to theme, theme_path(theme) %>
      </li>
    <% end %>
  </ul>
</p>

app/views/themes/show.html.erb
<%#
  Copyright 2018 Rosanna Gray
  Copyright 2019 Matthew B. Gray

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<h1>New Membership</h1>
<section class="l-section">
  <div class="row">
    <div class="col-12 col-md-8">
      <div class="l-panel">
        <h2>Sign Up</h2>
        <form action="" method="post" class="form form-m-membership" id="membership-form">
          <p>
            This charge will show as being from 'CoNZealand'. We are based in New Zealand, and use Stripe as our payment processor.
          </p>
          <fieldset>
            <legend>Member Details</legend>
            <div class="form-group">
            <label for="membership-type">Membership type</label>
            <select id="membership-type" name="MembershipType" class="form-control">
              <option value="" disabled>--Please choose an option--</option>
              <option value="Supporter">Supporter</option>
              <option value="Kid In Tow">Kid-In-Tow</option>
              <option value="Child">Child</option>
              <option value="Young Adult">Young Adult</option>
              <option value="Unwaged">Unwaged</option>
              <option value="Adult">Adult</option>
            </select>
            </div>
            <div class="form-group">
              <label for="member-legal-name">Legal Name <span class="required">*</span></label>
              <input type="text" name="MemberLegalName" id="member-legal-name" class="form-control form-control-m-error" required>
              <p class="form-error">
                Form error example - Please enter your legal name.
              </p>
              <p class="form-note">
                This is the name that appears on your official ID. We will need to check your ID at registration.
              </p>
            </div>
            <fieldset class="l-v-spacing">
              <div class="row">
                <div class="col-12 col-md-6">
                  <div class="form-group">
                    <label for="member-first-name">First Name <span class="required">*</span></label>
                    <input type="text" name="MemberFirstName" id="member-first-name" class="form-control" required>
                  </div>
                </div>
                <div class="col-12 col-md-6">
                  <div class="form-group">
                    <label for="member-last-name">Last Name <span class="required">*</span></label>
                    <input type="text" name="MemberLastName" id="member-last-name" class="form-control" required>
                  </div>
                </div>
              </div>
              <p class="form-note form-note-m-group">
                This is the name you would like to be addressed by. If it is left blank, you will be addressed by your legal name.
              </p>
            </fieldset>
            <div class="form-group">
              <label for="member-badge-name">Badge Name</label>
              <input type="text" name="MemberBadgeName" id="member-badge-name" class="form-control">
            </div>
            <div class="form-group">
              <label for="member-badge-subtitle">Badge Subtitle</label>
              <input type="text" name="MemberBadgeSubtitle" id="member-badge-subtitle" class="form-control">
            </div>
            <div class="form-group">
              <label for="member-email">Email <span class="required">*</span></label>
              <input type="email" name="MemberEmail" id="member-email" class="form-control" required>
              <p class="form-note">
                How we'll get in touch with you before the con, and where we'll send important information about the Hugo Awards and Worldcon Site Selection.
              </p>
            </div>
          </fieldset>
          <fieldset>
            <legend>Address</legend>
            <p class="form-note form-note-m-group">Where do you get your mail? This should match your credit card address, if you use one.</p>
            <div class="form-group">
              <label for="member-address-line1">Address Line 1 <span class="required">*</span></label>
              <input type="text" name="MemberAddressLine1" id="member-address-line1" class="form-control"required>
            </div>
            <div class="form-group">
              <label for="member-address-line2">Address Line 2</label>
              <input type="text" name="MemberAddressLine2" id="member-address-line2" class="form-control">
            </div>
            <div class="form-group">
              <label for="member-country">Country <span class="required">*</span></label>
              <input type="text" name="MemberCountry" id="member-country" class="form-control" required>
            </div>
          </fieldset>
          <fieldset>
            <legend>Other Details</legend>
            <p class="form-note form-note-m-group">
              Select an option - Radio buttons example
            </p>
            <div class="form-group">
              <div class="form-options">
                <input type="radio" id="radio-option-1" name="RadioGroup" value="Option 1" class="form-control form-control-m-radio">
                <label for="radio-option-1">Option 1</label>
              </div>
              <div class="form-options">
                <input type="radio" id="radio-option-2" name="RadioGroup" value="Option 2" class="form-control form-control-m-radio">
                <label for="radio-option-2">Option 2</label>
              </div>
              <div class="form-options">
                <input type="radio" id="radio-option-3" name="RadioGroup" value="Option 3" class="form-control form-control-m-radio">
                <label for="radio-option-2">Option 3</label>
              </div>
            </div>
          </fieldset>
          <fieldset>
            <legend>Other Details</legend>
            <p class="form-note form-note-m-group">
              Select multiple options - Checkboxes example
            </p>
            <div class="form-group">
              <div class="form-options">
                <input type="checkbox" id="checkbox-option-1" name="CheckboxGroup" value="Option 1" class="form-control form-control-m-checkbox">
                <label for="checkbox-option-1">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</label>
              </div>
              <div class="form-options">
                <input type="checkbox" id="checkbox-option-2" name="CheckboxGroup" value="Option 2" class="form-control form-control-m-checkbox">
                <label for="checkbox-option-1">
                  Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
                  Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
                  Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
                </label>
              </div>
              <div class="form-options">
                <input type="checkbox" id="checkbox-option-3" name="CheckboxGroup" value="Option 3" class="form-control form-control-m-checkbox">
                <label for="checkbox-option-3">Lorem Ipsum is simply dummy text.</label>
              </div>
            </div>
          </fieldset>
          <div class="l-v-spacing-both">
            <div class="form-group">
            <input type="submit" value="Sign Up" class="btn btn-m-full-width">
          </div>
          </div>
        </form>
      </div>
    </div>

    <div class="col-12 col-md-4">
      <div class="l-panel l-panel-m-membership-types">
        <h3>Membership Types</h3>
        <ul class="l-panel-m-membership-types--list">
          <li><h4 class="h6-like">Adult Membership</h4></li>
          <li><h4 class="h6-like">Young Adult Membership</h4>
            <p>born after 2000</p>
          </li>
          <li><h4 class="h6-like">Unwaged Membership</h4>
            <p>NZ residents only</p>
          </li>
          <li><h4 class="h6-like">Child Membership</h4>
            <p>born after 2005</p>
          </li>
          <li><h4 class="h6-like">Kid-in-tow</h4>
            <p>born after 2015</p>
          </li>
          <li><h4 class="h6-like">Supporting Membership</h4></li>
        </ul>
      </div>
    </div>
  </div>
</section>